### ISSUE TITLE
WARN

### ISSUE THREAD

**Issue by YuanYuanOwO** [BlvckBytes/QuickShopSearch#1]
```
[15:11:05 INFO]: Daylight_Yuan issued server command: /qss cake
[15:11:05 WARN]: java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
[15:11:05 WARN]:        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228)
[15:11:05 WARN]:        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232)
[15:11:05 WARN]:        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115)
[15:11:05 WARN]:        at java.base/java.lang.reflect.Field.set(Field.java:836)
[15:11:05 WARN]:        at QuickShopSearch-0.0.3.jar//me.blvckbytes.bukkitevaluable.ItemBuilder.applyHeadProfile(ItemBuilder.java:583)
[15:11:05 WARN]:        at QuickShopSearch-0.0.3.jar//me.blvckbytes.bukkitevaluable.ItemBuilder.applyTextures(ItemBuilder.java:541)
[15:11:05 WARN]:        at QuickShopSearch-0.0.3.jar//me.blvckbytes.bukkitevaluable.ItemBuilder.build(ItemBuilder.java:352)
[15:11:05 WARN]:        at QuickShopSearch-0.0.3.jar//me.blvckbytes.quick_shop_search.display.ResultDisplay.renderItems(ResultDisplay.java:248)
[15:11:05 WARN]:        at QuickShopSearch-0.0.3.jar//me.blvckbytes.quick_shop_search.display.ResultDisplay.show(ResultDisplay.java:216)
[15:11:05 WARN]:        at QuickShopSearch-0.0.3.jar//me.blvckbytes.quick_shop_search.display.ResultDisplay.<init>(ResultDisplay.java:83)
[15:11:05 WARN]:        at QuickShopSearch-0.0.3.jar//me.blvckbytes.quick_shop_search.display.ResultDisplayHandler.show(ResultDisplayHandler.java:40)
[15:11:05 WARN]:        at QuickShopSearch-0.0.3.jar//me.blvckbytes.quick_shop_search.QuickShopSearchCommand.lambda$onCommand$0(QuickShopSearchCommand.java:93)
[15:11:05 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[15:11:05 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:11:05 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:11:05 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:11:05 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:11:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[15:11:05 WARN]: java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
[15:11:05 WARN]:        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228)
[15:11:05 WARN]:        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232)
[15:11:05 WARN]:        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115)
[15:11:05 WARN]:        at java.base/java.lang.reflect.Field.set(Field.java:836)
[15:11:05 WARN]:        at QuickShopSearch-0.0.3.jar//me.blvckbytes.bukkitevaluable.ItemBuilder.applyHeadProfile(ItemBuilder.java:583)
[15:11:05 WARN]:        at QuickShopSearch-0.0.3.jar//me.blvckbytes.bukkitevaluable.ItemBuilder.applyTextures(ItemBuilder.java:541)
[15:11:05 WARN]:        at QuickShopSearch-0.0.3.jar//me.blvckbytes.bukkitevaluable.ItemBuilder.build(ItemBuilder.java:352)
[15:11:05 WARN]:        at QuickShopSearch-0.0.3.jar//me.blvckbytes.quick_shop_search.display.ResultDisplay.renderItems(ResultDisplay.java:253)
[15:11:05 WARN]:        at QuickShopSearch-0.0.3.jar//me.blvckbytes.quick_shop_search.display.ResultDisplay.show(ResultDisplay.java:216)
[15:11:05 WARN]:        at QuickShopSearch-0.0.3.jar//me.blvckbytes.quick_shop_search.display.ResultDisplay.<init>(ResultDisplay.java:83)
[15:11:05 WARN]:        at QuickShopSearch-0.0.3.jar//me.blvckbytes.quick_shop_search.display.ResultDisplayHandler.show(ResultDisplayHandler.java:40)
[15:11:05 WARN]:        at QuickShopSearch-0.0.3.jar//me.blvckbytes.quick_shop_search.QuickShopSearchCommand.lambda$onCommand$0(QuickShopSearchCommand.java:93)
[15:11:05 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[15:11:05 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:11:05 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:11:05 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:11:05 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:11:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by BlvckBytes** [comment]
How interesting! While I could find threads about this exact error online, I cannot seem to reproduce it... Do the textures of the backwards and forwards buttons render in your GUI? What exact server-version are you using?

**Comment by BlvckBytes** [comment]
Thank you, you're awesome! :) It worked fine on 1.21.1 build 40, and I can reproduce it now on build 99. I'll be looking into it and hopefully come up with a cross-version fix.

**Comment by BlvckBytes** [comment]
Please check whether the latest release removes this warning, and whether textures now render correctly.
