### ISSUE TITLE
some error?...

### ISSUE THREAD

**Issue by Luvucass** [BlvckBytes/QuickShopSearch#24]
[Mon 19:41:26 ERROR Minecraft] Could not pass event InventoryClickEvent to QSFindItemAddOn v2.0.7.2-RELEASE
java.lang.NoClassDefFoundError: com/earth2me/essentials/Essentials
    at QSFindItemAddOn-2.0.7.2-RELEASE.jar//io.myzticbean.finditemaddon.dependencies.EssentialsXPlugin.setLastLocation(EssentialsXPlugin.java:98)
    at QSFindItemAddOn-2.0.7.2-RELEASE.jar//io.myzticbean.finditemaddon.handlers.gui.menus.FoundShopsMenu.handleDirectShopTeleport(FoundShopsMenu.java:222)
    at QSFindItemAddOn-2.0.7.2-RELEASE.jar//io.myzticbean.finditemaddon.handlers.gui.menus.FoundShopsMenu.handleShopItemClick(FoundShopsMenu.java:175)
    at QSFindItemAddOn-2.0.7.2-RELEASE.jar//io.myzticbean.finditemaddon.handlers.gui.menus.FoundShopsMenu.handleMenu(FoundShopsMenu.java:121)
    at QSFindItemAddOn-2.0.7.2-RELEASE.jar//io.myzticbean.finditemaddon.listeners.MenuListener.onMenuClick(MenuListener.java:40)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor853.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3317)
    at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69)
    at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33)
    at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55)
    at net.minecraft.server

Idk how to fix this

**Comment by YuanYuanOwO** [comment]
WRONG REPO
https://github.com/myzticbean/QSFindItemAddOn
