### ISSUE TITLE
1.19.4 Paper issue

### ISSUE THREAD

**Issue by YuanYuanOwO** [BlvckBytes/QuickShopSearch#7]
```
[20:35:51] [Server thread/ERROR]: [QuickShopSearch] Could not initialize plugin
java.lang.IllegalStateException: Could not locate the CraftServer class
	at me.blvckbytes.quick_shop_search.bukkitevaluable.CommandUpdater.locateCraftServerClass(CommandUpdater.java:126) ~[QuickShopSearch-0.0.12-changed.jar:?]
	at me.blvckbytes.quick_shop_search.bukkitevaluable.CommandUpdater.<init>(CommandUpdater.java:32) ~[QuickShopSearch-0.0.12-changed.jar:?]
	at me.blvckbytes.quick_shop_search.QuickShopSearchPlugin.onEnable(QuickShopSearchPlugin.java:62) ~[QuickShopSearch-0.0.12-changed.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-550]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_19_R4.CraftServer
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:421) ~[?:?]
	at java.lang.Class.forName(Class.java:412) ~[?:?]
	at me.blvckbytes.quick_shop_search.bukkitevaluable.CommandUpdater.locateCraftServerClass(CommandUpdater.java:124) ~[QuickShopSearch-0.0.12-changed.jar:?]
	... 14 more
[20:35:51] [Server thread/INFO]: [QuickShopSearch] Disabling QuickShopSearch v0.0.12
```
same with 1.20.1&1.20.4&1.20.6

**Comment by BlvckBytes** [comment]
Should be fixed within the [latest release](https://github.com/BlvckBytes/QuickShopSearch/releases/tag/v0.0.13).
